### ISSUE TITLE
Update dependencies to remove vulnerabilities

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/google-discovery-to-swagger#13]
`npm audit fix --force` should do the trick

https://github.com/LucyBot-Inc/api-spec-converter/issues/208

**Comment by MikeRalphson** [comment]
@IvanGoncharov @RomanGotsiy as I don't have npm publish rights to this repository.

**Comment by IvanGoncharov** [comment]
@MikeRalphson I added you as maintainer.

**Comment by MikeRalphson** [comment]
@IvanGoncharov Thanks!

**Comment by cjolif** [comment]
any update?

**Comment by MikeRalphson** [comment]
Working on a new release, but I'm afraid it is not my top priority.

**Comment by MikeRalphson** [comment]
Published v2.1.0
