### ISSUE TITLE
`NO` and friends need to be escaped

### ISSUE THREAD

**Issue by armanbilge** [APIs-guru/google-discovery-to-swagger#22]
See for example https://github.com/APIs-guru/openapi-directory/blob/main/APIs/googleapis.com/bigquery/v2/openapi.yaml#L5036

There `NO` is supposed to be a string, but parsers read it as a boolean due to the YAML spec. In fact, there's several boolean-like strings you should be escaping: https://yaml.org/type/bool.html

Thanks for an awesome resource!

**Comment by MikeRalphson** [comment]
No, only YAML 1.1 has this issue. All current versions of OpenAPI recommend using YAML 1.2

**Comment by armanbilge** [comment]
Apologies, I wasn't aware of that. Thanks for the response, much appreciated!
