### ISSUE TITLE
Generate a root level tags property

### ISSUE THREAD

**Issue by crankydillo** [APIs-guru/google-discovery-to-swagger#8]
The code generates a tag at the operation level.  I'm under the impression there's a general expectation these refer to a root-level tags property, which contains more information (as in [petstore spec](http://petstore.swagger.io/v2/swagger.json)).

What do you think?

I'd be willing to write the code if you think it should be done.

**Comment by IvanGoncharov** [comment]
@crankydillo You right.
Swagger allow operations tags not marked on top-level, but I think it's good idea to also have them on top-level. 

> I'd be willing to write the code if you think it should be done.

It's pretty easy to add, so I will add this today :)

P.S. You try to convert one of Google's API spec?
If so please check my [main project](https://github.com/APIs-guru/api-models).
Or it some other API documented in this format?
If it public, can you please share the links?

**Comment by crankydillo** [comment]
woops, I didn't mean to do that:)

**Comment by crankydillo** [comment]
Sorry, but the specs I'm working on are private-ish.

**Comment by IvanGoncharov** [comment]
No problem.
When I wrote this converter I didn't expect that somebody outside of Google use it to document APIs :)

**Comment by crankydillo** [comment]
I think my company may have come to that conclusion as well:)

**Comment by IvanGoncharov** [comment]
@crankydillo Please test it and reopen if needed.

**Comment by crankydillo** [comment]
Preliminary testing looks good.  If I come across any issues with this, I'll let you know.

**Comment by crankydillo** [comment]
Wait, preliminary testing may not look good:)  I believe you might be duplicating tags if there are multiple paths for the same resource.  I don't mind submitting tests with issues, and as I've hinted, my team is looking to help with this tool.

How do you feel about unit testing?  Do you have a preference?  I'm a fan of [mocha](http://mochajs.org/) + [chai](http://chaijs.com/) (expect variant), but I'll use what you prefer.

**Comment by IvanGoncharov** [comment]
@crankydillo 
Sorry, for some reason missed email notification.

I will look into duplication issue, it should be very simple fix with LoDash.

> How do you feel about unit testing?

:+1: In my use case I'm focused only Google's specs, so unit-test can allow me to also consider 3rd-party spec during development.

 > I'm a fan of mocha + chai (expect variant), but I'll use what you prefer.

I'm new to JS(< 1year), and only thing that a worked with is `mocha + chai`.
So it totally ok for me.

> This is a sample of my typical style

Look good, except two things:
 - Indentation is inconsistent. And in this lib I use two spaces.
 - If you use big chunk of JSON more than 10-20 lines, please put it in separate file. Node allow you to require JSON files like that: `var gdTemplate = require('./gdTemplate.json');`

>  so I tend to use the functional programming capabilities of JS as compared to its OO

Same here, I can't leave without [LoDash](https://lodash.com/) :)

**Comment by IvanGoncharov** [comment]
@crankydillo Sorry totally forget to remove duplicate tags.
Fixed in cf293aff60f41ece67f0df62c0769c6e7d3c9297
